// Generated by https://quicktype.io

/**
 * Object Films that functions how
 * an container of Films
 */
class Films {
  // Film List with dynamic size
  List<Film> items = new List();

  // Empty Constructor
  Films();

  // Second Constructor to read json File
  Films.fromJsonList(List<dynamic> jsonList) {
    if (jsonList == null) return;

    // Iterative with items of JsonList
    for (var item in jsonList) {
      // Create an Film object with constructor
      // to receiver Json item.
      // Finally, only add the Film object
      // for the list.
      final film = new Film.fromJsonMap(item);
      items.add(film);
    }
  }
}

/**
 * Object FIlm in base on Json Response
 */
class Film {
  double popularity;
  int voteCount;
  bool video;
  String posterPath;
  int id;
  bool adult;
  String backdropPath;
  String originalLanguage;
  String originalTitle;
  List<int> genreIds;
  String title;
  double voteAverage;
  String overview;
  String releaseDate;

  Film({
    this.popularity,
    this.voteCount,
    this.video,
    this.posterPath,
    this.id,
    this.adult,
    this.backdropPath,
    this.originalLanguage,
    this.originalTitle,
    this.genreIds,
    this.title,
    this.voteAverage,
    this.overview,
    this.releaseDate,
  });

  /**
  * Second Construct to init variable on an result 
  * of json response
  */
  Film.fromJsonMap(Map<String, dynamic> json) {
    popularity = json['popularity'] / 1;
    voteCount = json['vote_count'];
    video = json['video'];
    posterPath = json['poster_path'];
    id = json['id'];
    adult = json['adult'];
    backdropPath = json['backdrop_path'];
    originalLanguage = json['original_language'];
    originalTitle = json['original_title'];
    genreIds = json['genre_ids'].cast<int>();
    title = json['title'];
    voteAverage = json['vote_average'] / 1;
    overview = json['overview'];
    releaseDate = json['release_date'];
  }

  String getPosterImg() {
    if (posterPath == null) {
      return "https://www.kubookstore.com/sca-dev-vinson/img/no_image_available.jpeg";
    }
    return "https://image.tmdb.org/t/p/w500/$posterPath";
  }
}
